### ISSUE TITLE
pls guide me how to install this project?

### ISSUE THREAD

**Issue by vanji-code** [Lilyah/laravel8-basics#1]

**Comment by Lilyah** [comment]
Hi, vanji-code!

Did you read the Readme.md file? It has section "Setup for local environment". Let me know if you followed the steps and didn't work.

**Comment by vanji-code** [comment]
> Hi, vanji-code!
> 
> Did you read the Readme.md file? It has section "Setup for local environment". Let me know if you followed the steps and didn't work.

Yes, but it shows error

Attempt to read property "title" on null (View: C:\xampp\htdocs\bhm\resources\views\home.blade.php)

C:\xampp\htdocs\bhm\resources\views/home.blade.php:18

<h2>{{ $abouts->title }}</h2>

**Comment by Lilyah** [comment]
Did you run 
`php artisan migrate`
so it can migrate all migrations and to create the db tables?

**Comment by Lilyah** [comment]
Also something in mind is that this project uses MySQL, so the confing file 
`/config/database.php`
search mysql db. If you are using other database management system (like PostgreSQL for example) you have to change some settings there.

**Comment by vanji-code** [comment]
> Did you run `php artisan migrate` so it can migrate all migrations and to create the db tables?

Yes, but how to seed the values? then only it shows "null" errors i think, meanwhile i use "?->" then its working but cannot "login" to backend pls guide

**Comment by Lilyah** [comment]
You can create your own values manually as a start. After you run `php artisan migrate` all the tables are empty, right? So you have to put some data in the tables. I see that you are using XAMPP, so you can open http://localhost/phpmyadmin/ and set the values that you need.

**Comment by vanji-code** [comment]
Ok, thank you for your help
